#
# Automatic Generated Makefile for Linux
#

all:	 shadercomp

shadercomp: base
	@echo --- shadercomp
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/shadercomp -f Makefile.shadercomp
	@echo Done.


# deps

base:
	@echo --- base
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/base -f Makefile.base


# faketargetall

clean:
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/shadercomp -f Makefile.shadercomp clean
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/base -f Makefile.base clean
	@echo Done.


# faketargetonce

