#
# Automatic Generated Makefile for Linux
#

all:	 asc

asc: base shadercomp
	@echo --- asc
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/tools/asc -f Makefile.asc
	@echo Done.


# deps

base:
	@echo --- base
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/base -f Makefile.base

shadercomp: base
	@echo --- shadercomp
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/shadercomp -f Makefile.shadercomp


# faketargetall

clean:
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/tools/asc -f Makefile.asc clean
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/base -f Makefile.base clean
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/shadercomp -f Makefile.shadercomp clean
	@echo Done.


# faketargetonce

