#
# Automatic Generated Makefile for Linux
#

all:	 util

util: base
	@echo --- util
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/util -f Makefile.util
	@echo Done.


# deps

base:
	@echo --- base
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/base -f Makefile.base


# faketargetall

clean:
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/util -f Makefile.util clean
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/base -f Makefile.base clean
	@echo Done.


# faketargetonce

