#
# Automatic Generated Makefile for Linux
#

all:	 wireapp

wireapp: gui util base
	@echo --- wireapp
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/examples/_gui/wireapp -f Makefile.wireapp
	@echo Done.


# deps

gui: base util
	@echo --- gui
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/gui -f Makefile.gui

util: base
	@echo --- util
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/util -f Makefile.util

base:
	@echo --- base
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/base -f Makefile.base


# faketargetall

clean:
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/examples/_gui/wireapp -f Makefile.wireapp clean
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/gui -f Makefile.gui clean
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/util -f Makefile.util clean
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/base -f Makefile.base clean
	@echo Done.


# faketargetonce

