#
# Automatic Generated Makefile for Linux
#

all:	 recttoy

recttoy: base util gui
	@echo --- recttoy
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/examples/_gui/recttoy -f Makefile.recttoy
	@echo Done.


# deps

base:
	@echo --- base
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/base -f Makefile.base

util: base
	@echo --- util
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/util -f Makefile.util

gui: base util
	@echo --- gui
	+@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/gui -f Makefile.gui


# faketargetall

clean:
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/examples/_gui/recttoy -f Makefile.recttoy clean
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/base -f Makefile.base clean
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/util -f Makefile.util clean
	@make -s --no-print-directory -C $(HOME)/fr_public/altona_wz4/altona/main/gui -f Makefile.gui clean
	@echo Done.


# faketargetonce

